#!/bin/bash

# Bash config
ln -rs ~/dotfiles/bash/bash_profile ~/.bash_profile
ln -rs ~/dotfiles/bash/bashrc ~/.bashrc
ln -rs ~/dotfiles/bash/inputrc ~/.inputrc

# Urxvt config
ln -rs ~/dotfiles/urxvt/Xdefaults ~/.Xdefaults

# Neovim config
ln -rs ~/dotfiles/vim/vimrc ~/.vimrc
ln -rs ~/dotfiles/vim/nvim ~/.config

# I3 config
ln -rs ~/dotfiles/i3 ~/.config

# Ctags config
ln -rs ~/dotfiles/ctags/ctags ~/.ctags

# Qutebrowser config
ln -rs ~/dotfiles/qutebrowser ~/.config
