#!/bin/sh
#
# Build setup copied taken from: https://sitr.us/2018/05/13/build-xmonad-with-stack.html
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -eux

stack build :my-xmonad
stack install :my-xmonad --local-bin-path bin/
mv bin/my-xmonad "$1"
